"""added the status field to the order and order items

Revision ID: 317cbd9e6f70
Revises: 1d097f4baba9
Create Date: 2025-09-03 15:49:30.246195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317cbd9e6f70'
down_revision: Union[str, Sequence[str], None] = '1d097f4baba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_status', sa.Text(), nullable=False , server_default="PENDING"))
    op.add_column('orders', sa.Column('order_status', sa.Text(), nullable=False , server_default="PENDING"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')
    op.drop_column('order_items', 'item_status')
    # ### end Alembic commands ###
